### ISSUE TITLE
Crock doesn't reads Config file .proc.json

### ISSUE THREAD

**Issue by dkudrin** [killercup/grock#30]
Hello,
grock 0.3.8 can't read .proc.json. It gets params only from command line arguments.

Best reagrds,
Dmitry

**Comment by dkudrin** [comment]
.proc.json is in the root of project. Grock globally installed.
Inside .proc.json:

```
{
  "glob": ["*.js"],
  "out": "docs",
  "verbose": "true",
  "style": "thin"
}
```

**Comment by killercup** [comment]
The config file is called `.groc.json` :)

**Comment by dkudrin** [comment]
@killercup Aha, thanks!)
